
import { Category, Library, Sponsor, SponsorTier } from '../types.ts';

export const Version = {
  INTERNAL: '0.0.2',
  PUBLIC: "v2026.02.02c(beta)",
};

export const SPONSORS: Sponsor[] = [
  { id: '1', name: 'Gold Sponsors Here', tier: SponsorTier.GOLD, url: '' },
  { id: '2', name: 'Silver Sponsors Here', tier: SponsorTier.SILVER, url: '' },
];

export const LIBRARIES: Library[] = [
  {
    id: 'retrofit',
    name: 'Retrofit',
    creator: 'Square',
    category: Category.NETWORKING,
    description: 'A type-safe HTTP client for Android and the JVM',
    stars: 43.9,
    latestVersion: '3.0.0',
    website: 'https://square.github.io/retrofit/',
    groupId: "com.squareup.retrofit2",
    nameId: "retrofit",
    varName: "retrofit",
    pros: ['Excellent community support', 'Powerful Interceptors via OkHttp'],
    cons: [''],
    alternatives: ['Ktor-Client', 'OkHttp'],
    commonIssues: [{ problem: "NetworkOnMainThreadException", fix: "Wrap calls in suspend functions or use Dispatchers.IO." }]
  },
  {
    id: 'ktor-client',
    name: 'Ktor Client',
    creator: 'Jetbrains',
    category: Category.NETWORKING,
    description: 'Multiplatform asynchronous HTTP client for Kotlin.',
    stars: 14.3,
    latestVersion: '3.4.0',
    website: 'https://ktor.io/docs/client.html',
    groupId: "io.ktor",
    varName: "ktorClient",
    nameId: "ktor-client-core",
    pros: ['Kotlin Multiplatform Support', 'Fully asynchronous', 'Highly customizable with plugins'],
    cons: ['Steeper learning curve than Retrofit', 'Verbose configuration'],
    alternatives: ['Retrofit', 'OkHttp'],
    commonIssues: [{ problem: "Missing Engine", fix: "Ensure an engine like Android, OkHttp, or CIO is provided to the client." }]
  },
  {
    id: 'okhttp',
    name: 'OkHttp',
    creator: 'Square',
    category: Category.NETWORKING,
    description: 'Square’s meticulous HTTP client for the JVM, Android, and GraalVM.',
    stars: 46.9,
    latestVersion: '5.3.2',
    website: 'https://square.github.io/okhttp/',
    groupId: "com.squareup.okhttp3",
    nameId: "okhttp",
    varName: "okhttp",
    pros: ['HTTP/2 and WebSocket support', 'Automatic GZIP', 'Connection pooling'],
    cons: ['Very low-level', 'No built-in JSON parsing'],
    alternatives: ['Retrofit', 'Volley'],
    commonIssues: [{ problem: "Leakage", fix: "Close response bodies in a finally block or use .use {}." }]
  },
  {
    id: 'apollo-kotlin',
    name: 'Apollo Kotlin',
    creator: "Apollo GraphQL",
    category: Category.NETWORKING,
    description: 'Strongly-typed, caching GraphQL client for Java/KMP.',
    stars: 3.9,
    latestVersion: '4.4.0',
    website: 'https://www.apollographql.com/docs/kotlin/',
    groupId: "com.apollographql.apollo",
    nameId: "apollo-runtime",
    varName: "apollo",
    pros: ['Strong type safety', 'Normalized caching', 'KMP ready'],
    cons: ['Requires code generation', 'Schema synchronization overhead'],
    alternatives: ['Retrofit', 'Ktor'],
    commonIssues: [{ problem: "Code gen fails", fix: "Check schema path and ensure the Apollo Gradle plugin is correctly applied." }]
  },
  {
    id: 'scarlet',
    name: 'Scarlet',
    creator: "Tinder",
    category: Category.NETWORKING,
    description: 'A Retrofit-inspired WebSocket client for Kotlin.',
    stars: 3.3,
    latestVersion: '0.1.12',
    website: 'https://github.com/Tinder/Scarlet',
    groupId: "com.tinder.scarlet",
    nameId: "scarlet",
    varName: "scarlet",
    pros: ['Declarative API', 'Lifecycle management', 'Reactive stream support'],
    cons: ['Beta status', 'Small community'],
    alternatives: ['OkHttp WebSockets'],
    commonIssues: [{ problem: "Disconnects", fix: "Use BackoffStrategy for reconnection logic." }]
  },

  // --- DEPENDENCY INJECTION ---
  {
    id: 'hilt',
    name: 'Hilt',
    creator: "Google",
    category: Category.DI,
    description: 'Standard DI library for Android, built on Dagger.',
    stars: 5.9,
    latestVersion: '2.59',
    website: 'https://dagger.dev/hilt/',
    groupId: "com.google.dagger",
    nameId: "hilt-android",
    varName: "hilt",
    pros: ['Standardized', 'ViewModel integration', 'Compile-time safety'],
    cons: ['Increases build times', 'Complex internals'],
    alternatives: ['Koin', 'Dagger 2'],
    commonIssues: [{ problem: "Missing @HiltAndroidApp", fix: "Ensure your Application class is annotated." }]
  },
  {
    id: 'koin',
    name: 'Koin',
    creator: "Replace",
    category: Category.DI,
    description: 'Pragmatic lightweight DI framework for Kotlin.',
    stars: 9.8,
    latestVersion: '4.1.1',
    website: 'https://insert-koin.io/',
    groupId: "io.insert-koin",
    nameId: "koin-android",
    varName: "koin",
    pros: ['No code generation', 'Simple DSL', 'Fast builds'],
    cons: ['Runtime dependency resolution', 'Performance cost for large graphs'],
    alternatives: ['Hilt', 'Kodein'],
    commonIssues: [{ problem: "DefinitionNotFoundException", fix: "Check if the module is included in startKoin." }]
  },
  {
    id: 'dagger2',
    name: 'Dagger 2',
    creator: "Google",
    category: Category.DI,
    description: 'A fast dependency injector for Java and Android.',
    stars: 17.7,
    latestVersion: '2.59',
    website: 'https://dagger.dev/',
    groupId: "com.google.dagger",
    nameId: "dagger",
    varName: "dagger",
    pros: ['Zero runtime overhead', 'Perfect compile-time safety', 'Proven at scale'],
    cons: ['Extremely steep learning curve', 'High boilerplate'],
    alternatives: ['Hilt', 'Anvil'],
    commonIssues: [{ problem: "Component issues", fix: "Use Hilt to simplify common Dagger patterns." }]
  },

  // --- UI & ANIMATIONS ---
  {
    id: 'lottie',
    name: 'Lottie',
    creator: "AirBnb",
    category: Category.UI,
    description: 'Render After Effects animations natively.',
    stars: 35.6,
    latestVersion: '6.7.1',
    website: 'https://airbnb.io/lottie/',
    groupId: "com.airbnb.android",
    nameId: "lottie",
    varName: "lottie",
    pros: ['Complex animations, small files', 'Interactive', 'Multi-platform'],
    cons: ['CPU intensive', 'Memory footprint'],
    alternatives: ['DotLottie'],
    commonIssues: [{ problem: "Not showing", fix: "Check if JSON is in 'raw' or 'assets' folder." }]
  },
  {
    id: 'shimmer',
    name: 'Shimmer-Android',
    creator: "Replace",
    category: Category.UI,
    description: 'An easy way to add a shimmer effect to any view.',
    stars: 15,
    latestVersion: '0.5.0',
    website: 'https://facebook.github.io/shimmer-android/',
    groupId: "com.facebook.shimmer",
    nameId: "shimmer",
    varName: "shimmer",
    pros: ['Proven UI pattern', 'Low overhead', 'Simple API'],
    cons: ['Maintenance slowed down', 'Native View based'],
    alternatives: ['Accompanist Placeholder'],
    commonIssues: [{ problem: "Memory usage", fix: "Stop shimmer animation in onPause/onStop." }]
  },
  {
    id: 'balloon',
    name: 'Balloon',
    creator: "Skydoves",
    category: Category.UI,
    description: 'Modern, lightweight tooltips for Android.',
    stars: 3.9,
    latestVersion: '1.7.3',
    website: 'https://github.com/skydoves/balloon',
    groupId: "com.github.skydoves",
    nameId: "balloon",
    varName: "balloon",
    pros: ['highly customizable', 'Lifecycle aware', 'Compose support'],
    cons: ['Additional dependency for simple tooltips'],
    alternatives: ['Material Tooltips'],
    commonIssues: [{ problem: "Positioning", fix: "Use .setArrowPosition() to align with anchor." }]
  },

  // --- DATABASE & PERSISTENCE ---
  {
    id: 'room',
    name: 'Room',
    creator: "Replace",
    category: Category.DATABASE,
    description: 'Standard SQLite abstraction for Android.',
    stars: 5.9,
    latestVersion: '2.8.4',
    website: 'https://developer.android.com/training/data-storage/room',
    groupId: "androidx.room",
    nameId: "room-runtime",
    varName: "room",
    pros: ['Compile-time SQL validation', 'Coroutine support', 'Easy migrations'],
    cons: ['Boilerplate', 'Strict schema'],
    alternatives: ['SQLDelight'],
    commonIssues: [{ problem: "Main thread query", fix: "Use Coroutines or .allowMainThreadQueries() (avoid)." }]
  },
  {
    id: 'sqldelight',
    name: 'SQLDelight',
    creator: "Cashapp",
    category: Category.DATABASE,
    description: 'Generates Kotlin APIs from your SQL statements.',
    stars: 6.7,
    latestVersion: '2.2.1',
    website: 'https://cashapp.github.io/sqldelight/',
    groupId: "app.cash.sqldelight",
    nameId: "android-driver",
    varName: "sqldelight",
    pros: ['SQL-first', 'KMP support', 'Zero boilerplate'],
    cons: ['Requires plugin setup', 'Manual SQL'],
    alternatives: ['Room'],
    commonIssues: [{ problem: "Plugin mismatch", fix: "Match Gradle plugin with runtime version." }]
  },

  // --- IMAGE LOADING ---
  {
    id: 'coil',
    name: 'Coil',
    creator: "Replace",
    category: Category.IMAGE_LOADING,
    description: 'Image loading backed by Kotlin Coroutines.',
    stars: 11.7,
    latestVersion: '3.3.0',
    website: 'https://coil-kt.github.io/coil/',
    groupId: "io.coil-kt.coil3",
    nameId: "coil-compose",
    varName: "coil",
    pros: ['Kotlin-first', 'Lightweight', 'Compose native'],
    cons: ['Smaller ecosystem than Glide'],
    alternatives: ['Glide', 'Picasso'],
    commonIssues: [{ problem: "Blurred images", fix: "Disable hardware bitmaps for transformations." }]
  },
  {
    id: 'glide',
    name: 'Glide',
    creator: "Bumptech",
    category: Category.IMAGE_LOADING,
    description: 'Fast and efficient open source media management framework.',
    stars: 35,
    latestVersion: '5.0.5',
    website: 'https://github.com/bumptech/glide',
    groupId: "com.github.bumptech.glide",
    nameId: "glide",
    varName: "glide",
    pros: ['Fast scrolling', 'GIF/Video support', 'Huge plugin ecosystem'],
    cons: ['Complex custom code', 'Code gen requirements'],
    alternatives: ['Coil', 'Fresco'],
    commonIssues: [{ problem: "Memory pressure", fix: "Use .thumbnail() for low-res placeholders." }]
  },
  {
    id: 'fresco',
    name: 'Fresco',
    creator: "Facebook",
    category: Category.IMAGE_LOADING,
    description: 'A powerful system for displaying images in Android by Meta.',
    stars: 17.1,
    latestVersion: '3.6.0',
    website: 'https://frescolib.org/',
    groupId: "com.facebook.fresco",
    nameId: "fresco",
    varName: "fresco",
    pros: ['Memory efficiency (Ashmem)', 'Progressive loading', 'WebP support'],
    cons: ['Heavy library size', 'Proprietary Drawee views'],
    alternatives: ['Glide', 'Coil'],
    commonIssues: [{ problem: "Initialization", fix: "Fresco.initialize(context) must be called once." }]
  },

  // --- UTILITIES ---
  {
    id: 'timber',
    name: 'Timber',
    creator: "JakeWharton",
    category: Category.UTILS,
    description: 'Extensible API for Android Log.',
    stars: 10.8,
    latestVersion: '5.0.1',
    website: 'https://github.com/JakeWharton/timber',
    groupId: "com.jakewharton.timber",
    nameId: "timber",
    varName: "timber",
    pros: ['Auto tagging', 'Prod-safe stripping', 'Clean API'],
    cons: ['Very basic'],
    alternatives: ['Napier'],
    commonIssues: [{ problem: "No logs", fix: "Plant DebugTree in Application onCreate." }]
  },
  {
    id: 'arrow',
    name: 'Arrow',
    creator: "Replace",
    category: Category.UTILS,
    description: 'Functional programming companion to Kotlin.',
    stars: 6.5,
    latestVersion: '2.2.1.1',
    website: 'https://arrow-kt.io/',
    groupId: "io.arrow-kt",
    nameId: "arrow-core",
    varName: "arrow",
    pros: ['Option/Either types', 'Typed errors', 'Immutability focus'],
    cons: ['Complex for beginners', 'Increases method count'],
    alternatives: ['Standard Kotlin Result'],
    commonIssues: [{ problem: "Verbosity", fix: "Use context receivers or typed error handling blocks." }]
  },

  // --- TESTING ---
  {
    id: 'mockk',
    name: 'MockK',
    creator: "Replace",
    category: Category.TESTING,
    description: 'Mocking library for Kotlin.',
    stars: 5.7,
    latestVersion: '1.14.9',
    website: 'https://mockk.io/',
    groupId: "io.mockk",
    nameId: "mockk",
    varName: "mockk",
    pros: ['Kotlin-first', 'Final class mocking', 'Coroutine support'],
    cons: ['Slower than Mockito'],
    alternatives: ['Mockito'],
    commonIssues: [{ problem: "Static leak", fix: "unmockkAll() after tests." }]
  },

  // --- ARCHITECTURE ---
  {
    id: 'mavericks',
    name: 'Mavericks',
    creator: "Replace",
    category: Category.ARCHITECTURE,
    description: 'MVI state management by Airbnb.',
    stars: 5.9,
    latestVersion: '3.0.13',
    website: 'https://airbnb.io/mavericks/',
    groupId: "com.airbnb.android",
    nameId: "mavericks",
    varName: "mavericks",
    pros: ['Predictable state', 'Large team scale', 'Rotation safe'],
    cons: ['Opinionated', 'Boilerplate'],
    alternatives: ['Orbit MVI'],
    commonIssues: [{ problem: "State loss", fix: "Make state Parcelable." }]
  },

  // --- DEVTOOLS ---
  {
    id: 'leakcanary',
    name: 'LeakCanary',
    creator: "Replace",
    category: Category.DEVTOOLS,
    description: 'Memory leak detection for Android.',
    stars: 29.9,
    latestVersion: '2.14',
    website: 'https://square.github.io/leakcanary/',
    groupId: "com.squareup.leakcanary",
    nameId: "leakcanary-android",
    varName: "leakcanary",
    pros: ['Auto detection', 'Detailed traces', 'Zero config'],
    cons: ['Debug only'],
    alternatives: ['Studio Profiler'],
    commonIssues: [{ problem: "Freezes", fix: "Normal during heap dump; ignore for development." }]
  },
  {
    id: 'chucker',
    name: 'Chucker',
    creator: "Replace",
    category: Category.DEVTOOLS,
    description: 'On-device HTTP inspector.',
    stars: 4.4,
    latestVersion: '4.3.0',
    website: 'https://github.com/ChuckerTeam/chucker',
    groupId: "com.github.chuckerteam.chucker",
    nameId: "library",
    varName: "chucker",
    pros: ['No PC sniffer needed', 'Easy log sharing', 'Secured activity'],
    cons: ['Increases debug APK size'],
    alternatives: ['Charles Proxy'],
    commonIssues: [{ problem: "Intercept fails", fix: "Add ChuckerInterceptor last in OkHttp." }]
  },
  {
    id: 'dotlottie-android',
    name: 'DotLottie',
    creator: "LottieFiles",
    category: Category.UI,
    description: 'A powerful Android library for rendering Lottie and dotLottie animations with advanced features like interactivity and theming.',
    stars: 0.1,
    latestVersion: '0.12.7',
    website: 'https://github.com/LottieFiles/dotlottie-android',
    groupId: "com.github.LottieFiles",
    nameId: "dotlottie-android",
    varName: "dotLottie",
    pros: ['More supported features'],
    cons: [''],
    alternatives: ['Lottie'],
    commonIssues: [{ problem: "", fix: "" }]
  },
  {
    id: 'mp-android-chart',
    name: 'MPAndroidChart',
    creator: "PhilJay",
    category: Category.UI,
    description: 'A powerful 🚀 Android chart view / graph view library, supporting line- bar- pie- radar- bubble- and candlestick charts as well as scaling, panning and animations.',
    stars: 38.2,
    latestVersion: 'v3.1.0',
    website: 'https://github.com/PhilJay/MPAndroidChart',
    groupId: "com.github.PhilJay",
    //jitpack
    nameId: "MPAndroidChart",
    varName: "mpAndroidChart",
    pros: [''],
    cons: [''],
    alternatives: [''],
    commonIssues: [{ problem: "", fix: "" }]
  },
  {
    id: 'calendar',
    name: 'Calendar',
    creator: "kizitonwose",
    category: Category.UI,
    description: 'A highly customizable calendar view and compose library for Android and Kotlin Multiplatform.',
    stars: 5.5,
    latestVersion: '2.10.0',
    website: 'https://github.com/kizitonwose/Calendar',
    groupId: "com.kizitonwose.calendar",
    //jitpack
    nameId: "compose",
    varName: "calendar",
    pros: [''],
    cons: [''],
    alternatives: [''],
    commonIssues: [{ problem: "", fix: "" }]
  }
];
